import { BabyName, ZodiacInfo, FruitSize, Testimonial, FAQItem, GoogleReview } from './types';

export const BABY_NAMES: BabyName[] = [
  // Mädchen - Klassisch
  { name: 'Anna', gender: 'Mädchen', style: 'Klassisch', meaning: 'zeitlos' },
  { name: 'Emma', gender: 'Mädchen', style: 'Klassisch', meaning: 'klassisch' },
  { name: 'Sofia', gender: 'Mädchen', style: 'Klassisch', meaning: 'elegant' },
  { name: 'Clara', gender: 'Mädchen', style: 'Klassisch', meaning: 'hell' },
  { name: 'Laura', gender: 'Mädchen', style: 'Klassisch', meaning: 'vertraut' },
  { name: 'Marie', gender: 'Mädchen', style: 'Klassisch', meaning: 'zeitlos' },
  { name: 'Elena', gender: 'Mädchen', style: 'Klassisch', meaning: 'weich' },
  { name: 'Julia', gender: 'Mädchen', style: 'Klassisch', meaning: 'klassisch' },
  { name: 'Lena', gender: 'Mädchen', style: 'Klassisch', meaning: 'sanft' },
  { name: 'Sarah', gender: 'Mädchen', style: 'Klassisch', meaning: 'bekannt' },
  { name: 'Hannah', gender: 'Mädchen', style: 'Klassisch', meaning: 'warm' },
  { name: 'Johanna', gender: 'Mädchen', style: 'Klassisch', meaning: 'traditionell' },
  { name: 'Katharina', gender: 'Mädchen', style: 'Klassisch', meaning: 'edel' },
  { name: 'Amalia', gender: 'Mädchen', style: 'Klassisch', meaning: 'vornehm' },
  { name: 'Theresa', gender: 'Mädchen', style: 'Klassisch', meaning: 'ruhig' },
  { name: 'Elisabeth', gender: 'Mädchen', style: 'Klassisch', meaning: 'klassisch' },
  { name: 'Franziska', gender: 'Mädchen', style: 'Klassisch', meaning: 'stark' },
  { name: 'Magdalena', gender: 'Mädchen', style: 'Klassisch', meaning: 'warm' },
  { name: 'Antonia', gender: 'Mädchen', style: 'Klassisch', meaning: 'edel' },
  { name: 'Josephine', gender: 'Mädchen', style: 'Klassisch', meaning: 'elegant' },
  { name: 'Charlotte', gender: 'Mädchen', style: 'Klassisch', meaning: 'vornehm' },
  { name: 'Luise', gender: 'Mädchen', style: 'Klassisch', meaning: 'sanft' },
  { name: 'Pauline', gender: 'Mädchen', style: 'Klassisch', meaning: 'freundlich' },
  { name: 'Mathilda', gender: 'Mädchen', style: 'Klassisch', meaning: 'traditionell' },
  { name: 'Helena', gender: 'Mädchen', style: 'Klassisch', meaning: 'hell' },
  { name: 'Victoria', gender: 'Mädchen', style: 'Klassisch', meaning: 'stark' },
  { name: 'Miriam', gender: 'Mädchen', style: 'Klassisch', meaning: 'ruhig' },
  { name: 'Rebecca', gender: 'Mädchen', style: 'Klassisch', meaning: 'vertraut' },
  { name: 'Isabel', gender: 'Mädchen', style: 'Klassisch', meaning: 'elegant' },
  { name: 'Annemarie', gender: 'Mädchen', style: 'Klassisch', meaning: 'zeitlos' },

  // Mädchen - Modern
  { name: 'Mila', gender: 'Mädchen', style: 'Modern', meaning: 'modern' },
  { name: 'Lia', gender: 'Mädchen', style: 'Modern', meaning: 'weich' },
  { name: 'Ella', gender: 'Mädchen', style: 'Modern', meaning: 'klar' },
  { name: 'Nora', gender: 'Mädchen', style: 'Modern', meaning: 'ruhig' },
  { name: 'Livia', gender: 'Mädchen', style: 'Modern', meaning: 'warm' },
  { name: 'Emilia', gender: 'Mädchen', style: 'Modern', meaning: 'beliebt' },
  { name: 'Amelie', gender: 'Mädchen', style: 'Modern', meaning: 'freundlich' },
  { name: 'Lina', gender: 'Mädchen', style: 'Modern', meaning: 'sanft' },
  { name: 'Ava', gender: 'Mädchen', style: 'Modern', meaning: 'modern' },
  { name: 'Mia', gender: 'Mädchen', style: 'Modern', meaning: 'kurz' },
  { name: 'Malea', gender: 'Mädchen', style: 'Modern', meaning: 'weich' },
  { name: 'Juna', gender: 'Mädchen', style: 'Modern', meaning: 'modern' },
  { name: 'Elina', gender: 'Mädchen', style: 'Modern', meaning: 'hell' },
  { name: 'Leni', gender: 'Mädchen', style: 'Modern', meaning: 'leicht' },
  { name: 'Malou', gender: 'Mädchen', style: 'Modern', meaning: 'sanft' },
  { name: 'Liyana', gender: 'Mädchen', style: 'Modern', meaning: 'weich' },
  { name: 'Enna', gender: 'Mädchen', style: 'Modern', meaning: 'klar' },
  { name: 'Mira', gender: 'Mädchen', style: 'Modern', meaning: 'ruhig' },
  { name: 'Nala', gender: 'Mädchen', style: 'Modern', meaning: 'warm' },
  { name: 'Romy', gender: 'Mädchen', style: 'Modern', meaning: 'freundlich' },
  { name: 'Leona', gender: 'Mädchen', style: 'Modern', meaning: 'stark' },
  { name: 'Mina', gender: 'Mädchen', style: 'Modern', meaning: 'sanft' },
  { name: 'Fina', gender: 'Mädchen', style: 'Modern', meaning: 'leicht' },
  { name: 'Liana', gender: 'Mädchen', style: 'Modern', meaning: 'elegant' },
  { name: 'Yara', gender: 'Mädchen', style: 'Modern', meaning: 'modern' },
  { name: 'Talia', gender: 'Mädchen', style: 'Modern', meaning: 'weich' },
  { name: 'Alina', gender: 'Mädchen', style: 'Modern', meaning: 'beliebt' },
  { name: 'Maila', gender: 'Mädchen', style: 'Modern', meaning: 'warm' },
  { name: 'Nelia', gender: 'Mädchen', style: 'Modern', meaning: 'sanft' },
  { name: 'Liviana', gender: 'Mädchen', style: 'Modern', meaning: 'modern' },

  // Mädchen - Kurz
  { name: 'Mia', gender: 'Mädchen', style: 'Kurz', meaning: 'kurz' },
  { name: 'Lia', gender: 'Mädchen', style: 'Kurz', meaning: 'kurz' },
  { name: 'Eva', gender: 'Mädchen', style: 'Kurz', meaning: 'klar' },
  { name: 'Lea', gender: 'Mädchen', style: 'Kurz', meaning: 'weich' },
  { name: 'Zoe', gender: 'Mädchen', style: 'Kurz', meaning: 'lebendig' },
  { name: 'Noa', gender: 'Mädchen', style: 'Kurz', meaning: 'modern' },
  { name: 'Liv', gender: 'Mädchen', style: 'Kurz', meaning: 'nordisch' },
  { name: 'Nia', gender: 'Mädchen', style: 'Kurz', meaning: 'sanft' },
  { name: 'Ela', gender: 'Mädchen', style: 'Kurz', meaning: 'leicht' },
  { name: 'Ida', gender: 'Mädchen', style: 'Kurz', meaning: 'klar' },
  { name: 'Amy', gender: 'Mädchen', style: 'Kurz', meaning: 'weich' },
  { name: 'Lou', gender: 'Mädchen', style: 'Kurz', meaning: 'kurz' },
  { name: 'Joy', gender: 'Mädchen', style: 'Kurz', meaning: 'hell' },
  { name: 'Ina', gender: 'Mädchen', style: 'Kurz', meaning: 'ruhig' },
  { name: 'Pia', gender: 'Mädchen', style: 'Kurz', meaning: 'freundlich' },
  { name: 'Ava', gender: 'Mädchen', style: 'Kurz', meaning: 'klar' },
  { name: 'Fia', gender: 'Mädchen', style: 'Kurz', meaning: 'leicht' },
  { name: 'Maja', gender: 'Mädchen', style: 'Kurz', meaning: 'warm' },
  { name: 'Mara', gender: 'Mädchen', style: 'Kurz', meaning: 'sanft' },
  { name: 'Lara', gender: 'Mädchen', style: 'Kurz', meaning: 'weich' },
  { name: 'Mira', gender: 'Mädchen', style: 'Kurz', meaning: 'ruhig' },
  { name: 'Lina', gender: 'Mädchen', style: 'Kurz', meaning: 'sanft' },
  { name: 'Enna', gender: 'Mädchen', style: 'Kurz', meaning: 'klar' },
  { name: 'Juna', gender: 'Mädchen', style: 'Kurz', meaning: 'modern' },
  { name: 'Leni', gender: 'Mädchen', style: 'Kurz', meaning: 'leicht' },
  { name: 'Nora', gender: 'Mädchen', style: 'Kurz', meaning: 'ruhig' },
  { name: 'Mila', gender: 'Mädchen', style: 'Kurz', meaning: 'modern' },
  { name: 'Elin', gender: 'Mädchen', style: 'Kurz', meaning: 'hell' },
  { name: 'Alma', gender: 'Mädchen', style: 'Kurz', meaning: 'warm' },
  { name: 'Thea', gender: 'Mädchen', style: 'Kurz', meaning: 'klar' },

  // Mädchen - Selten
  { name: 'Elin', gender: 'Mädchen', style: 'Selten', meaning: 'selten' },
  { name: 'Juna', gender: 'Mädchen', style: 'Selten', meaning: 'weich' },
  { name: 'Malea', gender: 'Mädchen', style: 'Selten', meaning: 'warm' },
  { name: 'Alva', gender: 'Mädchen', style: 'Selten', meaning: 'nordisch' },
  { name: 'Tilda', gender: 'Mädchen', style: 'Selten', meaning: 'freundlich' },
  { name: 'Anouk', gender: 'Mädchen', style: 'Selten', meaning: 'besonders' },
  { name: 'Malou', gender: 'Mädchen', style: 'Selten', meaning: 'weich' },
  { name: 'Enya', gender: 'Mädchen', style: 'Selten', meaning: 'sanft' },
  { name: 'Liora', gender: 'Mädchen', style: 'Selten', meaning: 'hell' },
  { name: 'Nela', gender: 'Mädchen', style: 'Selten', meaning: 'leicht' },
  { name: 'Ylvie', gender: 'Mädchen', style: 'Selten', meaning: 'nordisch' },
  { name: 'Aurelia', gender: 'Mädchen', style: 'Selten', meaning: 'edel' },
  { name: 'Svea', gender: 'Mädchen', style: 'Selten', meaning: 'klar' },
  { name: 'Milena', gender: 'Mädchen', style: 'Selten', meaning: 'weich' },
  { name: 'Soraya', gender: 'Mädchen', style: 'Selten', meaning: 'besonders' },
  { name: 'Elara', gender: 'Mädchen', style: 'Selten', meaning: 'hell' },
  { name: 'Levia', gender: 'Mädchen', style: 'Selten', meaning: 'sanft' },
  { name: 'Amira', gender: 'Mädchen', style: 'Selten', meaning: 'warm' },
  { name: 'Fenja', gender: 'Mädchen', style: 'Selten', meaning: 'stark' },
  { name: 'Ronja', gender: 'Mädchen', style: 'Selten', meaning: 'mutig' },
  { name: 'Jorina', gender: 'Mädchen', style: 'Selten', meaning: 'selten' },
  { name: 'Florina', gender: 'Mädchen', style: 'Selten', meaning: 'weich' },
  { name: 'Marla', gender: 'Mädchen', style: 'Selten', meaning: 'ruhig' },
  { name: 'Ilvy', gender: 'Mädchen', style: 'Selten', meaning: 'leicht' },
  { name: 'Lielle', gender: 'Mädchen', style: 'Selten', meaning: 'zart' },
  { name: 'Yuna', gender: 'Mädchen', style: 'Selten', meaning: 'modern' },
  { name: 'Samira', gender: 'Mädchen', style: 'Selten', meaning: 'warm' },
  { name: 'Melina', gender: 'Mädchen', style: 'Selten', meaning: 'sanft' },
  { name: 'Aurea', gender: 'Mädchen', style: 'Selten', meaning: 'edel' },
  { name: 'Naira', gender: 'Mädchen', style: 'Selten', meaning: 'besonders' },

  // Junge - Klassisch
  { name: 'Noah', gender: 'Junge', style: 'Klassisch', meaning: 'zeitlos' },
  { name: 'Elias', gender: 'Junge', style: 'Klassisch', meaning: 'klassisch' },
  { name: 'Leon', gender: 'Junge', style: 'Klassisch', meaning: 'stark' },
  { name: 'David', gender: 'Junge', style: 'Klassisch', meaning: 'vertraut' },
  { name: 'Samuel', gender: 'Junge', style: 'Klassisch', meaning: 'ruhig' },
  { name: 'Jonas', gender: 'Junge', style: 'Klassisch', meaning: 'freundlich' },
  { name: 'Lukas', gender: 'Junge', style: 'Klassisch', meaning: 'klassisch' },
  { name: 'Benjamin', gender: 'Junge', style: 'Klassisch', meaning: 'warm' },
  { name: 'Gabriel', gender: 'Junge', style: 'Klassisch', meaning: 'sanft' },
  { name: 'Simon', gender: 'Junge', style: 'Klassisch', meaning: 'klar' },
  { name: 'Daniel', gender: 'Junge', style: 'Klassisch', meaning: 'beständig' },
  { name: 'Alexander', gender: 'Junge', style: 'Klassisch', meaning: 'stark' },
  { name: 'Raphael', gender: 'Junge', style: 'Klassisch', meaning: 'sanft' },
  { name: 'Philipp', gender: 'Junge', style: 'Klassisch', meaning: 'klassisch' },
  { name: 'Maximilian', gender: 'Junge', style: 'Klassisch', meaning: 'edel' },
  { name: 'Johannes', gender: 'Junge', style: 'Klassisch', meaning: 'traditionell' },
  { name: 'Paul', gender: 'Junge', style: 'Klassisch', meaning: 'zeitlos' },
  { name: 'Jakob', gender: 'Junge', style: 'Klassisch', meaning: 'vertraut' },
  { name: 'Matthias', gender: 'Junge', style: 'Klassisch', meaning: 'ruhig' },
  { name: 'Sebastian', gender: 'Junge', style: 'Klassisch', meaning: 'stark' },
  { name: 'Valentin', gender: 'Junge', style: 'Klassisch', meaning: 'warm' },
  { name: 'Constantin', gender: 'Junge', style: 'Klassisch', meaning: 'edel' },
  { name: 'Julian', gender: 'Junge', style: 'Klassisch', meaning: 'bekannt' },
  { name: 'Michael', gender: 'Junge', style: 'Klassisch', meaning: 'klassisch' },
  { name: 'Tobias', gender: 'Junge', style: 'Klassisch', meaning: 'freundlich' },
  { name: 'Florian', gender: 'Junge', style: 'Klassisch', meaning: 'hell' },
  { name: 'Adrian', gender: 'Junge', style: 'Klassisch', meaning: 'klar' },
  { name: 'Christian', gender: 'Junge', style: 'Klassisch', meaning: 'traditionell' },
  { name: 'Niklas', gender: 'Junge', style: 'Klassisch', meaning: 'vertraut' },
  { name: 'Benedikt', gender: 'Junge', style: 'Klassisch', meaning: 'edel' },

  // Junge - Modern
  { name: 'Liam', gender: 'Junge', style: 'Modern', meaning: 'modern' },
  { name: 'Matteo', gender: 'Junge', style: 'Modern', meaning: 'warm' },
  { name: 'Leo', gender: 'Junge', style: 'Modern', meaning: 'kurz' },
  { name: 'Luca', gender: 'Junge', style: 'Modern', meaning: 'beliebt' },
  { name: 'Finn', gender: 'Junge', style: 'Modern', meaning: 'klar' },
  { name: 'Milo', gender: 'Junge', style: 'Modern', meaning: 'weich' },
  { name: 'Lio', gender: 'Junge', style: 'Modern', meaning: 'modern' },
  { name: 'Elio', gender: 'Junge', style: 'Modern', meaning: 'hell' },
  { name: 'Jaro', gender: 'Junge', style: 'Modern', meaning: 'selten' },
  { name: 'Levin', gender: 'Junge', style: 'Modern', meaning: 'freundlich' },
  { name: 'Leano', gender: 'Junge', style: 'Modern', meaning: 'warm' },
  { name: 'Milan', gender: 'Junge', style: 'Modern', meaning: 'modern' },
  { name: 'Kian', gender: 'Junge', style: 'Modern', meaning: 'klar' },
  { name: 'Neo', gender: 'Junge', style: 'Modern', meaning: 'kurz' },
  { name: 'Luan', gender: 'Junge', style: 'Modern', meaning: 'weich' },
  { name: 'Noel', gender: 'Junge', style: 'Modern', meaning: 'sanft' },
  { name: 'Jannis', gender: 'Junge', style: 'Modern', meaning: 'freundlich' },
  { name: 'Lias', gender: 'Junge', style: 'Modern', meaning: 'modern' },
  { name: 'Nilo', gender: 'Junge', style: 'Modern', meaning: 'leicht' },
  { name: 'Miro', gender: 'Junge', style: 'Modern', meaning: 'kreativ' },
  { name: 'Levi', gender: 'Junge', style: 'Modern', meaning: 'klar' },
  { name: 'Elian', gender: 'Junge', style: 'Modern', meaning: 'sanft' },
  { name: 'Jorin', gender: 'Junge', style: 'Modern', meaning: 'selten' },
  { name: 'Mika', gender: 'Junge', style: 'Modern', meaning: 'modern' },
  { name: 'Arin', gender: 'Junge', style: 'Modern', meaning: 'weich' },
  { name: 'Lenny', gender: 'Junge', style: 'Modern', meaning: 'freundlich' },
  { name: 'Matti', gender: 'Junge', style: 'Modern', meaning: 'warm' },
  { name: 'Nio', gender: 'Junge', style: 'Modern', meaning: 'kurz' },
  { name: 'Loris', gender: 'Junge', style: 'Modern', meaning: 'hell' },
  { name: 'Tino', gender: 'Junge', style: 'Modern', meaning: 'leicht' },

  // Junge - Kurz
  { name: 'Leo', gender: 'Junge', style: 'Kurz', meaning: 'kurz' },
  { name: 'Ben', gender: 'Junge', style: 'Kurz', meaning: 'kurz' },
  { name: 'Max', gender: 'Junge', style: 'Kurz', meaning: 'stark' },
  { name: 'Tim', gender: 'Junge', style: 'Kurz', meaning: 'klar' },
  { name: 'Jan', gender: 'Junge', style: 'Kurz', meaning: 'zeitlos' },
  { name: 'Tom', gender: 'Junge', style: 'Kurz', meaning: 'freundlich' },
  { name: 'Noé', gender: 'Junge', style: 'Kurz', meaning: 'weich' },
  { name: 'Lio', gender: 'Junge', style: 'Kurz', meaning: 'modern' },
  { name: 'Kai', gender: 'Junge', style: 'Kurz', meaning: 'klar' },
  { name: 'Nino', gender: 'Junge', style: 'Kurz', meaning: 'warm' },
  { name: 'Sam', gender: 'Junge', style: 'Kurz', meaning: 'kurz' },
  { name: 'Ian', gender: 'Junge', style: 'Kurz', meaning: 'leicht' },
  { name: 'Eli', gender: 'Junge', style: 'Kurz', meaning: 'sanft' },
  { name: 'Jon', gender: 'Junge', style: 'Kurz', meaning: 'klar' },
  { name: 'Teo', gender: 'Junge', style: 'Kurz', meaning: 'warm' },
  { name: 'Finn', gender: 'Junge', style: 'Kurz', meaning: 'klar' },
  { name: 'Luca', gender: 'Junge', style: 'Kurz', meaning: 'beliebt' },
  { name: 'Noah', gender: 'Junge', style: 'Kurz', meaning: 'zeitlos' },
  { name: 'Paul', gender: 'Junge', style: 'Kurz', meaning: 'klassisch' },
  { name: 'Emil', gender: 'Junge', style: 'Kurz', meaning: 'weich' },
  { name: 'Theo', gender: 'Junge', style: 'Kurz', meaning: 'warm' },
  { name: 'Levi', gender: 'Junge', style: 'Kurz', meaning: 'klar' },
  { name: 'Milo', gender: 'Junge', style: 'Kurz', meaning: 'sanft' },
  { name: 'Neo', gender: 'Junge', style: 'Kurz', meaning: 'modern' },
  { name: 'Mika', gender: 'Junge', style: 'Kurz', meaning: 'freundlich' },
  { name: 'Jona', gender: 'Junge', style: 'Kurz', meaning: 'sanft' },
  { name: 'Aris', gender: 'Junge', style: 'Kurz', meaning: 'hell' },
  { name: 'Nio', gender: 'Junge', style: 'Kurz', meaning: 'kurz' },
  { name: 'Timo', gender: 'Junge', style: 'Kurz', meaning: 'leicht' },
  { name: 'Linus', gender: 'Junge', style: 'Kurz', meaning: 'ruhig' },

  // Junge - Selten
  { name: 'Jorin', gender: 'Junge', style: 'Selten', meaning: 'selten' },
  { name: 'Elian', gender: 'Junge', style: 'Selten', meaning: 'sanft' },
  { name: 'Arvid', gender: 'Junge', style: 'Selten', meaning: 'nordisch' },
  { name: 'Luan', gender: 'Junge', style: 'Selten', meaning: 'weich' },
  { name: 'Kian', gender: 'Junge', style: 'Selten', meaning: 'modern' },
  { name: 'Leano', gender: 'Junge', style: 'Selten', meaning: 'warm' },
  { name: 'Silas', gender: 'Junge', style: 'Selten', meaning: 'ruhig' },
  { name: 'Miro', gender: 'Junge', style: 'Selten', meaning: 'kreativ' },
  { name: 'Nilo', gender: 'Junge', style: 'Selten', meaning: 'leicht' },
  { name: 'Aurel', gender: 'Junge', style: 'Selten', meaning: 'edel' },
  { name: 'Joris', gender: 'Junge', style: 'Selten', meaning: 'besonders' },
  { name: 'Tamino', gender: 'Junge', style: 'Selten', meaning: 'musikalisch' },
  { name: 'Levin', gender: 'Junge', style: 'Selten', meaning: 'freundlich' },
  { name: 'Nuri', gender: 'Junge', style: 'Selten', meaning: 'hell' },
  { name: 'Ilian', gender: 'Junge', style: 'Selten', meaning: 'weich' },
  { name: 'Anian', gender: 'Junge', style: 'Selten', meaning: 'selten' },
  { name: 'Florin', gender: 'Junge', style: 'Selten', meaning: 'hell' },
  { name: 'Caspar', gender: 'Junge', style: 'Selten', meaning: 'edel' },
  { name: 'Laurin', gender: 'Junge', style: 'Selten', meaning: 'sagenhaft' },
  { name: 'Leander', gender: 'Junge', style: 'Selten', meaning: 'stark' },
  { name: 'Kilian', gender: 'Junge', style: 'Selten', meaning: 'klar' },
  { name: 'Marlon', gender: 'Junge', style: 'Selten', meaning: 'modern' },
  { name: 'Remo', gender: 'Junge', style: 'Selten', meaning: 'ruhig' },
  { name: 'Samu', gender: 'Junge', style: 'Selten', meaning: 'weich' },
  { name: 'Taro', gender: 'Junge', style: 'Selten', meaning: 'leicht' },
  { name: 'Elion', gender: 'Junge', style: 'Selten', meaning: 'hell' },
  { name: 'Jaron', gender: 'Junge', style: 'Selten', meaning: 'warm' },
  { name: 'Milan', gender: 'Junge', style: 'Selten', meaning: 'modern' },
  { name: 'Oskar', gender: 'Junge', style: 'Selten', meaning: 'klar' },
  { name: 'Rune', gender: 'Junge', style: 'Selten', meaning: 'nordisch' },

  // Beides - Klassisch
  { name: 'Alex', gender: 'Beides', style: 'Klassisch', meaning: 'klassisch' },
  { name: 'Robin', gender: 'Beides', style: 'Klassisch', meaning: 'zeitlos' },
  { name: 'Kim', gender: 'Beides', style: 'Klassisch', meaning: 'kurz' },
  { name: 'Toni', gender: 'Beides', style: 'Klassisch', meaning: 'freundlich' },
  { name: 'Dominique', gender: 'Beides', style: 'Klassisch', meaning: 'vertraut' },
  { name: 'Andrea', gender: 'Beides', style: 'Klassisch', meaning: 'klassisch' },
  { name: 'Sascha', gender: 'Beides', style: 'Klassisch', meaning: 'bekannt' },
  { name: 'Mika', gender: 'Beides', style: 'Klassisch', meaning: 'modern' },
  { name: 'Chris', gender: 'Beides', style: 'Klassisch', meaning: 'kurz' },
  { name: 'Simone', gender: 'Beides', style: 'Klassisch', meaning: 'weich' },
  { name: 'Luca', gender: 'Beides', style: 'Klassisch', meaning: 'bekannt' },
  { name: 'Jamie', gender: 'Beides', style: 'Klassisch', meaning: 'freundlich' },
  { name: 'René', gender: 'Beides', style: 'Klassisch', meaning: 'klassisch' },
  { name: 'Noa', gender: 'Beides', style: 'Klassisch', meaning: 'weich' },
  { name: 'Manu', gender: 'Beides', style: 'Klassisch', meaning: 'vertraut' },
  { name: 'Charlie', gender: 'Beides', style: 'Klassisch', meaning: 'warm' },
  { name: 'Sam', gender: 'Beides', style: 'Klassisch', meaning: 'klar' },
  { name: 'Jona', gender: 'Beides', style: 'Klassisch', meaning: 'sanft' },
  { name: 'Elia', gender: 'Beides', style: 'Klassisch', meaning: 'warm' },
  { name: 'Lou', gender: 'Beides', style: 'Klassisch', meaning: 'kurz' },
  { name: 'Jan', gender: 'Beides', style: 'Klassisch', meaning: 'zeitlos' },
  { name: 'Claude', gender: 'Beides', style: 'Klassisch', meaning: 'klassisch' },
  { name: 'Francis', gender: 'Beides', style: 'Klassisch', meaning: 'ruhig' },
  { name: 'Marian', gender: 'Beides', style: 'Klassisch', meaning: 'weich' },
  { name: 'Nicola', gender: 'Beides', style: 'Klassisch', meaning: 'vertraut' },
  { name: 'Noel', gender: 'Beides', style: 'Klassisch', meaning: 'warm' },
  { name: 'Dani', gender: 'Beides', style: 'Klassisch', meaning: 'freundlich' },
  { name: 'Michi', gender: 'Beides', style: 'Klassisch', meaning: 'vertraut' },
  { name: 'Sasha', gender: 'Beides', style: 'Klassisch', meaning: 'bekannt' },
  { name: 'Stevie', gender: 'Beides', style: 'Klassisch', meaning: 'freundlich' },

  // Beides - Modern
  { name: 'Lou', gender: 'Beides', style: 'Modern', meaning: 'weich' },
  { name: 'Noa', gender: 'Beides', style: 'Modern', meaning: 'modern' },
  { name: 'Jona', gender: 'Beides', style: 'Modern', meaning: 'sanft' },
  { name: 'Mika', gender: 'Beides', style: 'Modern', meaning: 'klar' },
  { name: 'Elia', gender: 'Beides', style: 'Modern', meaning: 'warm' },
  { name: 'Lian', gender: 'Beides', style: 'Modern', meaning: 'leicht' },
  { name: 'Milan', gender: 'Beides', style: 'Modern', meaning: 'modern' },
  { name: 'Kaya', gender: 'Beides', style: 'Modern', meaning: 'weich' },
  { name: 'Nika', gender: 'Beides', style: 'Modern', meaning: 'selten' },
  { name: 'Charlie', gender: 'Beides', style: 'Modern', meaning: 'modern' },
  { name: 'Rio', gender: 'Beides', style: 'Modern', meaning: 'leicht' },
  { name: 'Neo', gender: 'Beides', style: 'Modern', meaning: 'klar' },
  { name: 'Eden', gender: 'Beides', style: 'Modern', meaning: 'hell' },
  { name: 'Lio', gender: 'Beides', style: 'Modern', meaning: 'modern' },
  { name: 'Ari', gender: 'Beides', style: 'Modern', meaning: 'kurz' },
  { name: 'Elin', gender: 'Beides', style: 'Modern', meaning: 'hell' },
  { name: 'Yael', gender: 'Beides', style: 'Modern', meaning: 'weich' },
  { name: 'Marlo', gender: 'Beides', style: 'Modern', meaning: 'modern' },
  { name: 'Jori', gender: 'Beides', style: 'Modern', meaning: 'leicht' },
  { name: 'Lior', gender: 'Beides', style: 'Modern', meaning: 'sanft' },
  { name: 'Nuri', gender: 'Beides', style: 'Modern', meaning: 'selten' },
  { name: 'Aiko', gender: 'Beides', style: 'Modern', meaning: 'besonders' },
  { name: 'Loan', gender: 'Beides', style: 'Modern', meaning: 'weich' },
  { name: 'Ilay', gender: 'Beides', style: 'Modern', meaning: 'sanft' },
  { name: 'Robin', gender: 'Beides', style: 'Modern', meaning: 'zeitlos' },
  { name: 'Riley', gender: 'Beides', style: 'Modern', meaning: 'modern' },
  { name: 'Quinn', gender: 'Beides', style: 'Modern', meaning: 'klar' },
  { name: 'Avery', gender: 'Beides', style: 'Modern', meaning: 'hell' },
  { name: 'Sky', gender: 'Beides', style: 'Modern', meaning: 'leicht' },
  { name: 'Casey', gender: 'Beides', style: 'Modern', meaning: 'weich' },

  // Beides - Kurz
  { name: 'Lou', gender: 'Beides', style: 'Kurz', meaning: 'kurz' },
  { name: 'Kim', gender: 'Beides', style: 'Kurz', meaning: 'kurz' },
  { name: 'Sam', gender: 'Beides', style: 'Kurz', meaning: 'klar' },
  { name: 'Max', gender: 'Beides', style: 'Kurz', meaning: 'stark' },
  { name: 'Noa', gender: 'Beides', style: 'Kurz', meaning: 'weich' },
  { name: 'Eli', gender: 'Beides', style: 'Kurz', meaning: 'leicht' },
  { name: 'Jan', gender: 'Beides', style: 'Kurz', meaning: 'zeitlos' },
  { name: 'Ari', gender: 'Beides', style: 'Kurz', meaning: 'hell' },
  { name: 'Neo', gender: 'Beides', style: 'Kurz', meaning: 'modern' },
  { name: 'Kai', gender: 'Beides', style: 'Kurz', meaning: 'klar' },
  { name: 'Rio', gender: 'Beides', style: 'Kurz', meaning: 'leicht' },
  { name: 'Bo', gender: 'Beides', style: 'Kurz', meaning: 'kurz' },
  { name: 'Jo', gender: 'Beides', style: 'Kurz', meaning: 'freundlich' },
  { name: 'Lee', gender: 'Beides', style: 'Kurz', meaning: 'sanft' },
  { name: 'Lex', gender: 'Beides', style: 'Kurz', meaning: 'stark' },
  { name: 'Mika', gender: 'Beides', style: 'Kurz', meaning: 'klar' },
  { name: 'Lio', gender: 'Beides', style: 'Kurz', meaning: 'modern' },
  { name: 'Nio', gender: 'Beides', style: 'Kurz', meaning: 'kurz' },
  { name: 'Loui', gender: 'Beides', style: 'Kurz', meaning: 'weich' },
  { name: 'Toni', gender: 'Beides', style: 'Kurz', meaning: 'freundlich' },
  { name: 'Alex', gender: 'Beides', style: 'Kurz', meaning: 'klassisch' },
  { name: 'Chris', gender: 'Beides', style: 'Kurz', meaning: 'kurz' },
  { name: 'Jona', gender: 'Beides', style: 'Kurz', meaning: 'sanft' },
  { name: 'Elia', gender: 'Beides', style: 'Kurz', meaning: 'warm' },
  { name: 'Nika', gender: 'Beides', style: 'Kurz', meaning: 'selten' },
  { name: 'Kimy', gender: 'Beides', style: 'Kurz', meaning: 'leicht' },
  { name: 'Noé', gender: 'Beides', style: 'Kurz', meaning: 'weich' },
  { name: 'Remy', gender: 'Beides', style: 'Kurz', meaning: 'sanft' },
  { name: 'Robin', gender: 'Beides', style: 'Kurz', meaning: 'zeitlos' },
  { name: 'Manu', gender: 'Beides', style: 'Kurz', meaning: 'vertraut' },

  // Beides - Selten
  { name: 'Nuri', gender: 'Beides', style: 'Selten', meaning: 'selten' },
  { name: 'Yael', gender: 'Beides', style: 'Selten', meaning: 'weich' },
  { name: 'Elin', gender: 'Beides', style: 'Selten', meaning: 'hell' },
  { name: 'Jori', gender: 'Beides', style: 'Selten', meaning: 'leicht' },
  { name: 'Lior', gender: 'Beides', style: 'Selten', meaning: 'sanft' },
  { name: 'Malin', gender: 'Beides', style: 'Selten', meaning: 'nordisch' },
  { name: 'Noel', gender: 'Beides', style: 'Selten', meaning: 'warm' },
  { name: 'Luca', gender: 'Beides', style: 'Selten', meaning: 'bekannt' },
  { name: 'Aiko', gender: 'Beides', style: 'Selten', meaning: 'besonders' },
  { name: 'Rio', gender: 'Beides', style: 'Selten', meaning: 'leicht' },
  { name: 'Yuki', gender: 'Beides', style: 'Selten', meaning: 'hell' },
  { name: 'Sorell', gender: 'Beides', style: 'Selten', meaning: 'selten' },
  { name: 'Loan', gender: 'Beides', style: 'Selten', meaning: 'weich' },
  { name: 'Ilay', gender: 'Beides', style: 'Selten', meaning: 'sanft' },
  { name: 'Marlo', gender: 'Beides', style: 'Selten', meaning: 'modern' },
  { name: 'Ari', gender: 'Beides', style: 'Selten', meaning: 'kurz' },
  { name: 'Eden', gender: 'Beides', style: 'Selten', meaning: 'hell' },
  { name: 'Kaya', gender: 'Beides', style: 'Selten', meaning: 'weich' },
  { name: 'Nika', gender: 'Beides', style: 'Selten', meaning: 'besonders' },
  { name: 'Rowan', gender: 'Beides', style: 'Selten', meaning: 'naturverbunden' },
  { name: 'Quinn', gender: 'Beides', style: 'Selten', meaning: 'klar' },
  { name: 'Avery', gender: 'Beides', style: 'Selten', meaning: 'hell' },
  { name: 'Sky', gender: 'Beides', style: 'Selten', meaning: 'leicht' },
  { name: 'Juno', gender: 'Beides', style: 'Selten', meaning: 'modern' },
  { name: 'Elia', gender: 'Beides', style: 'Selten', meaning: 'warm' },
  { name: 'Lian', gender: 'Beides', style: 'Selten', meaning: 'leicht' },
  { name: 'Milan', gender: 'Beides', style: 'Selten', meaning: 'modern' },
  { name: 'Mika', gender: 'Beides', style: 'Selten', meaning: 'klar' },
  { name: 'Lou', gender: 'Beides', style: 'Selten', meaning: 'weich' },
  { name: 'Noa', gender: 'Beides', style: 'Selten', meaning: 'modern' }
];

export const ZODIACS: ZodiacInfo[] = [
  {
    name: 'Widder',
    icon: '♈',
    dateRange: '21.03. - 19.04.',
    pregnancyQuote: 'Widder: Voller Energie, Tatendrang und ungeduldig, das neue Abenteuer Leben zu beginnen.',
    personality: 'voller Tatendrang, mutig und abenteuerlustig'
  },
  {
    name: 'Stier',
    icon: '♉',
    dateRange: '20.04. - 20.05.',
    pregnancyQuote: 'Stier: Ausgeglichen, naturverbunden und genussvoll – du machst es dir im Nest richtig gemütlich.',
    personality: 'geduldig, zuverlässig und sehr genussvoll'
  },
  {
    name: 'Zwillinge',
    icon: '♊',
    dateRange: '21.05. - 20.06.',
    pregnancyQuote: 'Zwillinge: Neugierig, kommunikativ und ständig am Lesen aller Schwangerschaftsbücher.',
    personality: 'neugierig, kommunikativ und geistig vielseitig'
  },
  {
    name: 'Krebs',
    icon: '♋',
    dateRange: '21.06. - 22.07.',
    pregnancyQuote: 'Krebs: Tief emotional, fürsorglich und am Dekorieren des schönsten Babyzimmers der Welt.',
    personality: 'sensibel, beschützend und absolut familienbezogen'
  },
  {
    name: 'Löwe',
    icon: '♌',
    dateRange: '23.07. - 22.08.',
    pregnancyQuote: 'Löwe: Stolz, beschützend und mit einer natürlichen Schwangerschafts-Aura, die alle anzieht.',
    personality: 'selbstbewusst, warmherzig und stolz'
  },
  {
    name: 'Jungfrau',
    icon: '♍',
    dateRange: '23.08. - 22.09.',
    pregnancyQuote: 'Jungfrau: Perfekt organisiert, strukturiert und hat bereits alle Kliniktaschen-Listen dreifach geprüft.',
    personality: 'klug, zuverlässig und sehr detailorientiert'
  },
  {
    name: 'Waage',
    icon: '♎',
    dateRange: '23.09. - 22.10.',
    pregnancyQuote: 'Waage: Harmoniesuchend, diplomatisch und wählt den Babynamen nach dem schönsten Klang aus.',
    personality: 'harmoniebedürftig, charmant und ausgesprochen gerecht'
  },
  {
    name: 'Skorpion',
    icon: '♏',
    dateRange: '23.10. - 21.11.',
    pregnancyQuote: 'Skorpion: Intensiv, beschützend und mit einem unfehlbaren Bauchgefühl für die Bedürfnisse des Babys.',
    personality: 'willensstark, tief und voller starkem Gefühl'
  },
  {
    name: 'Schütze',
    icon: '♐',
    dateRange: '22.11. - 21.12.',
    pregnancyQuote: 'Schütze: Unverbesserlich optimistisch, reiselustig und freut sich schon auf die grossen Abenteuer zu dritt.',
    personality: 'optimistisch, freiheitsliebend und weise'
  },
  {
    name: 'Steinbock',
    icon: '♑',
    dateRange: '22.12. - 19.01.',
    pregnancyQuote: 'Steinbock: Verantwortungsbewusst, diszipliniert und plant die finanzielle Zukunft des Babys vorausschauend.',
    personality: 'ehrgeizig, ausdauernd und absolut pflichtbewusst'
  },
  {
    name: 'Wassermann',
    icon: '♒',
    dateRange: '20.01. - 18.02.',
    pregnancyQuote: 'Wassermann: Unkonventionell, kreativ und findet ganz besondere, kreative Lösungsansätze im Familienalltag.',
    personality: 'unabhängig, kreativ und zukunftsorientiert'
  },
  {
    name: 'Fische',
    icon: '♓',
    dateRange: '19.02. - 20.03.',
    pregnancyQuote: 'Fische: Verträumt, hochsensibel und verbindet sich schon in der Schwangerschaft tief spirituell mit dem Baby.',
    personality: 'einfühlsam, träumerisch und voller Fantasie'
  }
];

export const FRUIT_SIZES: FruitSize[] = [
  { weekMin: 0, weekMax: 7, fruit: 'Samenkorn', size: 'ca. 2-5 mm', weight: 'ca. 1g', emoji: '🌱' },
  { weekMin: 8, weekMax: 11, fruit: 'Himbeere', size: 'ca. 1.6 - 3 cm', weight: 'ca. 1 - 4g', emoji: '🍓' },
  { weekMin: 12, weekMax: 15, fruit: 'Limette', size: 'ca. 5.4 - 8.5 cm', weight: 'ca. 14 - 45g', emoji: '🍋' },
  { weekMin: 16, weekMax: 19, fruit: 'Avocado', size: 'ca. 11.6 - 14.2 cm', weight: 'ca. 100 - 190g', emoji: '🥑' },
  { weekMin: 20, weekMax: 23, fruit: 'Banane', size: 'ca. 25 - 29 cm', weight: 'ca. 300 - 500g', emoji: '🍌' },
  { weekMin: 24, weekMax: 27, fruit: 'Maiskolben', size: 'ca. 30 - 34 cm', weight: 'ca. 600 - 900g', emoji: '🌽' },
  { weekMin: 28, weekMax: 31, fruit: 'Aubergine', size: 'ca. 37 - 41 cm', weight: 'ca. 1000 - 1500g', emoji: '🍆' },
  { weekMin: 32, weekMax: 35, fruit: 'Kürbis', size: 'ca. 42 - 46 cm', weight: 'ca. 1700 - 2300g', emoji: '🎃' },
  { weekMin: 36, weekMax: 39, fruit: 'Honigmelone', size: 'ca. 47 - 50 cm', weight: 'ca. 2600 - 3200g', emoji: '🍈' },
  { weekMin: 40, weekMax: 50, fruit: 'Wassermelone', size: 'ca. 51 - 53 cm', weight: 'ca. 3400 - 3800g', emoji: '🍉' }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    quote: '„Der Baby-Check von FINWIWO hat uns extreme Sicherheit gegeben. Wir wussten davor gar nicht, dass eine spätere Ablehnung der Zusatzversicherung wegen kleiner Geburtskomplikationen so häufig ist. Jetzt ist unsere kleine Emily perfekt versichert, und die Beratung war super sympathisch.“',
    author: 'Sarah & Michael',
    role: 'Werdende Eltern',
    location: 'Zürich',
    isHebamme: false
  },
  {
    quote: '„Als freischaffende Hebamme sehe ich im Alltag oft, dass sich Paare erst nach der Geburt um Zusatzversicherungen kümmern. Wenn das Baby dann einen unruhigen Start hat, ist der Zug für viele tolle Zusatzdeckungen abgefahren. Die frühzeitige Anmeldung spart enormen Stress.“',
    author: 'Karin S.',
    role: 'Hebamme HF',
    location: 'St. Gallen',
    isHebamme: true
  },
  {
    quote: '„Ich hatte anfangs Bedenken, ob die Beratung wirklich unabhängig und kostenfrei ist. Aber FINWIWO vergleicht sachlich alle Kassen. Wir sparen dank des empfohlenen Familienrabatts über CHF 60.- jeden Monat und haben zudem das Starter-Set geschenkt bekommen.“',
    author: 'Julia & Thomas',
    role: 'Werdende Eltern',
    location: 'Winterthur',
    isHebamme: false
  }
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    id: 1,
    question: 'Wann ist der späteste Zeitpunkt für eine vorgeburtliche Anmeldung?',
    answer: 'Sinnvoll ist das zweite Schwangerschaftsdrittel (ca. 13. bis 28. Woche). Viele Kassen nehmen die Anmeldung bis kurz vor der Geburt entgegen. Je früher, desto entspannter. Nach der Geburt startet für Zusatzversicherungen oft eine strenge Gesundheitsprüfung, die zu Ausschlüssen oder Ablehnungen führen kann.'
  },
  {
    id: 2,
    question: 'Was passiert, wenn mein Baby mit einem Geburtsthema zur Welt kommt?',
    answer: 'Bei Zusatzversicherungen können nach der Geburt Gesundheitsfragen entscheidend sein. Wurde das Baby nicht bereits vorgeburtlich ohne Prüfung angemeldet, kann es bei angeborenen Krankheiten, Frühgeburt oder kleineren Komplikationen zu einer Ablehnung, einem Vorbehalt oder einer Wartezeit kommen. Vorgeburtlich ist der Zugang ohne Gesundheitsprüfung garantiert.'
  },
  {
    id: 3,
    question: 'Zahlt die Grundversicherung die halbprivate oder private Abteilung?',
    answer: 'Nein. Die gesetzliche Grundversicherung (KVG) übernimmt ausschliesslich die Behandlung in der allgemeinen Abteilung im Wohnkanton. Wenn du dein Kind halbprivat oder privat im Spital versichern möchtest (freie Arztwahl, Zweitbett- oder Einbettzimmer), benötigst du eine Zusatzversicherung (VVG). Genau darum ist die vorgeburtliche Anmeldung so wichtig.'
  },
  {
    id: 4,
    question: 'Muss mein Baby bei derselben Kasse versichert sein wie ich?',
    answer: 'Nein. Es gibt keinerlei Verpflichtung, das Baby bei deiner aktuellen Krankenkasse anzumelden. Oft macht es sogar grossen Sinn, das Baby separat bei einer Kasse zu versichern, die besonders vorteilhafte Kinderkonditionen, grosszügige Geburtspauschalen oder stärkere Zahnleistungen anbietet. Wir vergleichen alle Angebote vollkommen unabhängig für dich.'
  },
  {
    id: 5,
    question: 'Was kostet eine Zusatzversicherung fürs Baby?',
    answer: 'Das ist je nach gewünschtem Leistungsumfang (Zahn, Komplementärmedizin, Spitalzusatz) und Kasse unterschiedlich. Da das Risiko bei Babys statistisch noch gering ist, sind Baby-Zusatzversicherungen oft überraschend günstig (oft nur wenige Franken pro Monat). Häufig gibt es auch attraktive Familienrabatte ab dem 2. Kind.'
  },
  {
    id: 6,
    question: 'Bekomme ich wirklich bis zu CHF 3\'500 Geburtspauschale?',
    answer: 'Die genaue Höhe der Auszahlung hängt ganz vom gewählten Versicherungsprodukt und den genauen Versicherungsbedingungen der jeweiligen Kasse ab. Zum Beispiel zahlt das CSS Spital Baby grosszügige Beiträge, sofern die Bedingungen erfüllt sind. Deshalb kommunizieren wir absolut transparent mit „bis zu CHF 3\'500“ und prüfen im Beratungstermin gemeinsam, wo du den grössten Nutzen hast.'
  },
  {
    id: 7,
    question: 'Kann ich mein Baby nach der Geburt noch in eine bessere Lösung wechseln?',
    answer: 'Ein Wechsel nach der Geburt ist grundsätzlich möglich, unterliegt dann aber der vollen Gesundheitsprüfung. Hat das Baby bis dahin Allergien, Atemwegserkrankungen oder andere Befunde entwickelt, wird die Aufnahme oft abgelehnt. Deshalb ist die vorgeburtliche Anmeldung der sicherste, einfachste und stressfreiste Weg.'
  }
];

export const FINWIWO_GOOGLE_REVIEWS: GoogleReview[] = [
  {
    author: "Nicoletta M.",
    rating: 5,
    date: "Vor 3 Monaten",
    text: "Alessandro Palermo hat mich äusserst kompetent und freundlich beraten. Er nimmt sich extrem viel Zeit, geht auf alle individuellen Wünsche ein und erklärt komplexe Finanz- und Versicherungsthemen verständlich und transparent. Man fühlt sich zu jeder Zeit bestens aufgehoben und absolut ehrlich beraten. Wärmstens zu empfehlen!",
    avatarBg: "bg-teal text-white"
  },
  {
    author: "Marc B.",
    rating: 5,
    date: "Vor 2 Monaten",
    text: "Top Beratung für die vorgeburtliche Krankenkassenanmeldung unseres Babys! Herr Palermo hat uns die Unterschiede sachlich aufgezeigt und die perfekte Lösung gefunden. Alles unkompliziert, unabhängig und super freundlich.",
    avatarBg: "bg-coral text-white"
  },
  {
    author: "Sabrina K.",
    rating: 5,
    date: "Vor 1 Monat",
    text: "Sehr professioneller Service. Ich habe schnell Antworten erhalten und fühlte mich zu keinem Zeitpunkt gedrängt. FINWIWO hat die gesamte Abwicklung übernommen. Wirklich ein toller Co-Pilot für Finanz- und Vorsorgefragen!",
    avatarBg: "bg-teal-deep text-white"
  }
];
